name: test
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'   

      - run: poetry sync --no-interaction

      - run: poetry run pytest -q tests/