name: test
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --sync --no-interaction

      - name: Run tests
        run: poetry run pytest -q tests/
