name: test
on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: |
          export POETRY_HOME="$HOME/poetry"
          curl -sSL https://install.python-poetry.org | python - -y
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH

      - name: Debug Poetry path
        run: |
          echo "PATH=$PATH"
          echo "$POETRY_HOME/bin"
          ls -l "$POETRY_HOME/bin"

      - name: Install dependencies
        run: poetry install --sync --no-interaction

      - name: Run tests
        run: poetry run pytest -q tests/